// Generated by CoffeeScript 1.9.3
(function() {
  exports.run = function(argv) {
    var clone_to, fetcher, params, repository_url, usage;
    usage = "Usage:\n iojs " + process.argv[1] + " <repository> <directory> [--branch master] \noptions: \n--branch\t branch to fetch (like in git clone --branch), default 'master' \n--help\t\t show this help";
    params = argv.slice(2);
    repository_url = params[0];
    clone_to = params[1];
    argv = require('minimist')(params.slice(2), {
      boolean: ['help'],
      string: ['branch'],
      "default": {
        branch: 'master'
      },
      unknown: function(param) {
        console.log("don't know " + param);
        console.log(usage);
        return process.exit();
      }
    });
    if (argv.help) {
      console.log(usage);
    }
    fetcher = require('./fetch');
    console.log(repository_url, clone_to);
    console.dir(argv);
    return fetcher.run(repository_url, clone_to, argv);
  };

}).call(this);

//# sourceMappingURL=fetch_runner.js.map
