// Generated by CoffeeScript 1.9.3
(function() {
  exports.run = function(argv) {
    var clone_to, fetcher, params, parsedArgs, preParse, repository_url, usage;
    usage = "Usage:\n iojs " + process.argv[1] + " <repository> <directory> [--branch master] \noptions: \n--branch\t branch to fetch (like in git clone --branch), default 'master' \n--help\t\t show this help \n--version\t\t";
    params = argv.slice(2);
    repository_url = params[0];
    clone_to = params[1];
    preParse = require('minimist')(argv, {
      boolean: ['version', 'help']
    });
    if (preParse.help) {
      console.log(usage);
      process.exit();
    }
    if (preParse.version) {
      console.log(require('../package').version);
      process.exit();
    }
    parsedArgs = require('minimist')(params.slice(2), {
      boolean: ['help', 'version'],
      string: ['branch'],
      "default": {
        branch: 'master'
      },
      unknown: function(param) {
        console.log("don't know " + param);
        console.log(usage);
        return process.exit();
      }
    });
    fetcher = require('./fetch');
    return fetcher.run(repository_url, clone_to, argv);
  };

}).call(this);

//# sourceMappingURL=fetch_runner.js.map
